const DEFAULT_PRODUCTS=[
 {id:1,name:"Ração Premium Cães 10 kg",category:"Alimentação",animal:"Cachorro",price:129.9,stock:18,min:5,icon:"bone",image:"dog-care.png",desc:"Nutrição completa para cães adultos."},
 {id:2,name:"Ração Premium Gatos 3 kg",category:"Alimentação",animal:"Gato",price:84.9,stock:14,min:5,icon:"cat",image:"cat-vet.png",desc:"Fórmula balanceada para gatos adultos."},
 {id:3,name:"Ração para Coelhos 1 kg",category:"Alimentação",animal:"Outros",price:29.9,stock:9,min:4,icon:"rabbit",image:"other-pets.png",desc:"Alimento completo rico em fibras."},
 {id:4,name:"Alimento para Peixes",category:"Alimentação",animal:"Outros",price:19.9,stock:16,min:5,icon:"fish",image:"other-pets.png",desc:"Flocos para peixes ornamentais."},
 {id:5,name:"Petisco Natural para Cães",category:"Petiscos",animal:"Cachorro",price:22.9,stock:4,min:5,icon:"cookie",image:"dog-care.png",desc:"Petisco assado com ingredientes naturais."},
 {id:6,name:"Petisco Cremoso para Gatos",category:"Petiscos",animal:"Gato",price:14.9,stock:11,min:4,icon:"milk",image:"cat-vet.png",desc:"Snack cremoso de alta aceitação."},
 {id:7,name:"Shampoo Pele Sensível",category:"Higiene",animal:"Cachorro",price:35.9,stock:3,min:5,icon:"bath",image:"petclub-service.png",desc:"Limpeza suave e hidratação."},
 {id:8,name:"Areia Higiênica 4 kg",category:"Higiene",animal:"Gato",price:32.9,stock:20,min:6,icon:"package",image:"cat-vet.png",desc:"Alta absorção e controle de odores."},
 {id:9,name:"Tapete Higiênico 30 un.",category:"Higiene",animal:"Cachorro",price:59.9,stock:8,min:5,icon:"layers",image:"petclub-store.png",desc:"Proteção e absorção para o dia a dia."},
 {id:10,name:"Antipulgas Cães",category:"Medicamentos",animal:"Cachorro",price:54.9,stock:6,min:4,icon:"shield-plus",image:"dog-care.png",desc:"Uso demonstrativo sob orientação veterinária."},
 {id:11,name:"Antipulgas Gatos",category:"Medicamentos",animal:"Gato",price:49.9,stock:5,min:4,icon:"shield-plus",image:"cat-vet.png",desc:"Uso demonstrativo sob orientação veterinária."},
 {id:12,name:"Coleira Confort",category:"Acessórios",animal:"Cachorro",price:45,stock:12,min:4,icon:"badge",image:"petclub-store.png",desc:"Ajustável, resistente e confortável."},
 {id:13,name:"Caixa de Transporte",category:"Acessórios",animal:"Todos",price:139.9,stock:7,min:3,icon:"briefcase",image:"petclub-store.png",desc:"Transporte seguro para cães e gatos."},
 {id:14,name:"Bebedouro Automático",category:"Utensílios",animal:"Todos",price:89.9,stock:10,min:3,icon:"cup-soda",image:"petclub-store.png",desc:"Água fresca e circulação contínua."},
 {id:15,name:"Comedouro Inox",category:"Utensílios",animal:"Todos",price:34.9,stock:15,min:5,icon:"circle",image:"petclub-store.png",desc:"Higiênico e fácil de limpar."},
 {id:16,name:"Bola Resistente",category:"Brinquedos",animal:"Cachorro",price:24.9,stock:13,min:5,icon:"circle-dot",image:"dog-care.png",desc:"Diversão e estímulo para cães."},
 {id:17,name:"Arranhador Compacto",category:"Brinquedos",animal:"Gato",price:79.9,stock:6,min:3,icon:"sparkles",image:"cat-vet.png",desc:"Ajuda a preservar móveis e estimular o gato."},
 {id:18,name:"Brinquedo Interativo",category:"Brinquedos",animal:"Todos",price:39.9,stock:9,min:4,icon:"puzzle",image:"petclub-store.png",desc:"Enriquecimento ambiental e atividade mental."},
 {id:19,name:"Brinquedo para Aves",category:"Brinquedos",animal:"Outros",price:27.9,stock:8,min:3,icon:"bird",image:"other-pets.png",desc:"Estimula atividade e curiosidade."},
 {id:20,name:"Roda para Hamster",category:"Brinquedos",animal:"Outros",price:42.9,stock:5,min:3,icon:"circle-gauge",image:"other-pets.png",desc:"Exercício seguro para pequenos roedores."},
 {id:21,name:"Cama Macia Tamanho M",category:"Acessórios",animal:"Todos",price:99.9,stock:7,min:3,icon:"bed",image:"petclub-store.png",desc:"Conforto para o descanso do seu pet."},
 {id:22,name:"Kit Aquário Inicial",category:"Utensílios",animal:"Outros",price:189.9,stock:4,min:2,icon:"fish-symbol",image:"other-pets.png",desc:"Kit demonstrativo para começar um aquário."}
];
const SERVICES=[
 {id:1,animal:"Cachorro",name:"Banho completo",price:55,duration:"1h",icon:"bath",desc:"Banho, hidratação, secagem, escovação e perfume."},
 {id:2,animal:"Cachorro",name:"Banho e tosa",price:85,duration:"1h30",icon:"scissors",desc:"Tosa personalizada e acabamento profissional."},
 {id:3,animal:"Cachorro",name:"Tosa higiênica",price:45,duration:"45 min",icon:"sparkles",desc:"Higiene, conforto e cuidados essenciais."},
 {id:4,animal:"Cachorro",name:"Hidratação de pelagem",price:40,duration:"40 min",icon:"droplets",desc:"Tratamento para brilho e maciez."},
 {id:5,animal:"Cachorro",name:"Consulta veterinária",price:120,duration:"45 min",icon:"stethoscope",desc:"Avaliação clínica e orientações."},
 {id:6,animal:"Cachorro",name:"Vacinação canina",price:90,duration:"30 min",icon:"syringe",desc:"Aplicação e registro demonstrativo de vacina."},
 {id:7,animal:"Gato",name:"Banho felino",price:70,duration:"1h",icon:"bath",desc:"Higiene delicada em ambiente tranquilo."},
 {id:8,animal:"Gato",name:"Escovação e unhas",price:42,duration:"40 min",icon:"brush",desc:"Remoção de pelos soltos e corte de unhas."},
 {id:9,animal:"Gato",name:"Consulta felina",price:130,duration:"45 min",icon:"stethoscope",desc:"Atendimento específico para felinos."},
 {id:10,animal:"Gato",name:"Vacinação felina",price:95,duration:"30 min",icon:"syringe",desc:"Aplicação e atualização da carteirinha."},
 {id:11,animal:"Gato",name:"Controle de pulgas",price:55,duration:"30 min",icon:"shield-plus",desc:"Avaliação e orientação preventiva."},
 {id:12,animal:"Outros",name:"Consulta para aves",price:140,duration:"50 min",icon:"bird",desc:"Avaliação demonstrativa para aves."},
 {id:13,animal:"Outros",name:"Consulta para roedores",price:135,duration:"50 min",icon:"mouse",desc:"Avaliação para coelhos e pequenos roedores."},
 {id:14,animal:"Outros",name:"Orientação para aquários",price:75,duration:"40 min",icon:"fish",desc:"Cuidados com alimentação e ambiente."},
 {id:15,animal:"Todos",name:"Higiene bucal",price:45,duration:"30 min",icon:"smile",desc:"Cuidado preventivo e orientação."},
 {id:16,animal:"Todos",name:"Atendimento emergencial 24h",price:180,duration:"Prioritário",icon:"siren",desc:"Triagem e avaliação emergencial demonstrativa."}
];
const INITIAL_PETS=[{id:1,name:"Thor",species:"Cachorro",breed:"Golden Retriever",age:"4 anos",gender:"Macho",weight:"31 kg",notes:"Sem alergias conhecidas"},{id:2,name:"Mia",species:"Gato",breed:"Siamês",age:"2 anos",gender:"Fêmea",weight:"4 kg",notes:"Sensível a ambientes barulhentos"}];
const INITIAL_BOOKINGS=[{id:101,pet:"Thor",animal:"Cachorro",service:"Banho completo",professional:"Ana — Estética",date:"2026-08-27",time:"09:30",notes:"Usar shampoo suave",status:"Confirmado",price:55},{id:102,pet:"Mia",animal:"Gato",service:"Vacinação felina",professional:"Dr. Lucas — Veterinário",date:"2026-08-27",time:"11:00",notes:"Retorno anual",status:"Em atendimento",price:95}];
const INITIAL_ORDERS=[{id:"PC-2026-0141",customer:"Carlos Souza",date:"26/08/2026",total:120,status:"Pago",items:1},{id:"PC-2026-0140",customer:"Ana Lima",date:"25/08/2026",total:174.8,status:"Entregue",items:3}];
const clone=v=>JSON.parse(JSON.stringify(v));
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??clone(fallback)}catch{return clone(fallback)}};
let products=load("pc_products",DEFAULT_PRODUCTS),cart=load("pc_cart",[]),pets=load("pc_pets",INITIAL_PETS),bookings=load("pc_bookings",INITIAL_BOOKINGS),orders=load("pc_orders",INITIAL_ORDERS),restocks=load("pc_restocks",[]),adminRecords=load("pc_admin_records",[]);
let filters={category:"Todos",animal:"Todos",service:"Todos"},adminSection="dashboard";
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
const save=()=>{localStorage.setItem("pc_products",JSON.stringify(products));localStorage.setItem("pc_cart",JSON.stringify(cart));localStorage.setItem("pc_pets",JSON.stringify(pets));localStorage.setItem("pc_bookings",JSON.stringify(bookings));localStorage.setItem("pc_orders",JSON.stringify(orders));localStorage.setItem("pc_restocks",JSON.stringify(restocks));localStorage.setItem("pc_admin_records",JSON.stringify(adminRecords))};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function refreshIcons(){if(window.lucide)lucide.createIcons()}
function toast(message){$("#toast span").textContent=message;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2700)}
function go(page){$$(".page").forEach(x=>x.classList.remove("active"));$("#page-"+page).classList.add("active");$("#mobileNav").classList.remove("open");window.scrollTo({top:0,behavior:"smooth"});
if(page==="shop")renderShop();
if(page==="services")renderServices();refreshIcons()}
function openModal(id){$("#"+id).classList.add("open");refreshIcons()}
function closeModal(id){$("#"+id).classList.remove("open")}
function openDrawer(){renderCart();$("#cartDrawer").classList.add("open");$("#overlay").classList.add("show")}
function closeDrawer(){ $("#cartDrawer").classList.remove("open");$("#overlay").classList.remove("show")}

function renderServices(){
 const animals=["Todos","Cachorro","Gato","Outros"];
 $("#serviceFilters").innerHTML=animals.map(a=>`<button class="${filters.service===a?"active":""}" data-service-filter="${a}">${a}</button>`).join("");
 const list=SERVICES.filter(s=>filters.service==="Todos"||s.animal===filters.service||s.animal==="Todos");
 $("#serviceCatalog").innerHTML=list.map(s=>`<article class="service-card"><div class="service-top"><i data-lucide="${s.icon}"></i></div><div class="service-info"><small>${s.animal.toUpperCase()} • ${s.duration}</small><h3>${s.name}</h3><p>${s.desc}</p><div class="service-meta"><strong>A partir de ${money(s.price)}</strong><button data-book-service="${s.id}">Agendar</button></div></div></article>`).join("");
 $$("[data-service-filter]").forEach(b=>b.onclick=()=>{filters.service=b.dataset.serviceFilter;renderServices()});
 $$("[data-book-service]").forEach(b=>b.onclick=()=>prepareSchedule(Number(b.dataset.bookService)));refreshIcons();
}
function categories(){return["Todos",...new Set(products.map(p=>p.category))]}
function animals(){return["Todos","Cachorro","Gato","Outros"]}
function renderShop(){
 $("#categoryFilters").innerHTML=categories().map(x=>`<button class="${filters.category===x?"active":""}" data-cat="${x}">${x}</button>`).join("");
 $("#animalFilters").innerHTML=animals().map(x=>`<button class="${filters.animal===x?"active":""}" data-animal-filter="${x}">${x}</button>`).join("");
 let list=products.filter(p=>(filters.category==="Todos"||p.category===filters.category)&&(filters.animal==="Todos"||p.animal===filters.animal||p.animal==="Todos"));
 const q=$("#productSearch")?.value.toLowerCase()||"";list=list.filter(p=>(p.name+p.desc+p.category).toLowerCase().includes(q));
 const sort=$("#sortProducts")?.value||"name";list.sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:a.name.localeCompare(b.name));
 $("#productCount").textContent=list.length+" produtos encontrados";
 $("#productGrid").innerHTML=list.map(p=>`<article class="product-card"><div class="product-visual"><img src="assets/${p.image}" alt="${p.name}"></div><span class="stock-tag ${p.stock===0?"out":p.stock<=p.min?"low":""}">${p.stock===0?"Esgotado":p.stock+" em estoque"}</span><div class="product-info"><small>${p.category.toUpperCase()} • ${p.animal}</small><h3>${p.name}</h3><p>${p.desc}</p><div class="product-buy"><strong>${money(p.price)}</strong><button data-add="${p.id}" ${p.stock===0?"disabled":""} aria-label="Adicionar ao carrinho"><i data-lucide="plus"></i></button></div></div></article>`).join("");
 $$("[data-cat]").forEach(b=>b.onclick=()=>{filters.category=b.dataset.cat;renderShop()});$$("[data-animal-filter]").forEach(b=>b.onclick=()=>{filters.animal=b.dataset.animalFilter;renderShop()});$$("[data-add]").forEach(b=>b.onclick=()=>addToCart(Number(b.dataset.add)));refreshIcons();
}
function addToCart(id){const product=products.find(p=>p.id===id),item=cart.find(i=>i.id===id),qty=item?.qty||0;
if(qty>=product.stock)return toast("Quantidade máxima disponível atingida");
if(item)item.qty++;else cart.push({id,qty:1});save();updateCartCount();toast(product.name+" adicionado ao carrinho")}
function updateCartCount(){$("#cartCount").textContent=cart.reduce((s,i)=>s+i.qty,0)}
function cartTotal(){return cart.reduce((s,i)=>s+(products.find(p=>p.id===i.id)?.price||0)*i.qty,0)}
function renderCart(){
 if(!cart.length){$("#cartItems").innerHTML=`<div class="empty-state"><i data-lucide="shopping-cart"></i><h3>Seu carrinho está vazio</h3><p>Adicione produtos da loja para continuar.</p><button class="btn teal" onclick="closeDrawer();go('shop')">Ver produtos</button></div>`;$("#cartFooter").innerHTML="";refreshIcons();return}
 $("#cartItems").innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);return`<div class="cart-item"><span class="mini"><i data-lucide="${p.icon}"></i></span><div><h4>${p.name}</h4><small>${money(p.price)} cada</small><div class="qty"><button data-qty="${p.id}" data-delta="-1">−</button><b>${i.qty}</b><button data-qty="${p.id}" data-delta="1">+</button></div></div><button class="remove" data-remove="${p.id}"><i data-lucide="trash-2"></i></button></div>`}).join("");
 $("#cartFooter").innerHTML=`<div class="total-line"><span>Subtotal</span><strong>${money(cartTotal())}</strong></div><button class="btn coral" id="checkoutBtn">Ir para o checkout</button>`;
 $$("[data-qty]").forEach(b=>b.onclick=()=>changeQty(Number(b.dataset.qty),Number(b.dataset.delta)));$$("[data-remove]").forEach(b=>b.onclick=()=>{cart=cart.filter(i=>i.id!==Number(b.dataset.remove));save();updateCartCount();renderCart()});$("#checkoutBtn").onclick=startCheckout;refreshIcons();
}
function changeQty(id,delta){const item=cart.find(i=>i.id===id),p=products.find(x=>x.id===id);item.qty=Math.max(0,Math.min(p.stock,item.qty+delta));
if(!item.qty)cart=cart.filter(i=>i.id!==id);save();updateCartCount();renderCart()}
function startCheckout(){closeDrawer();$("#checkoutSummary").innerHTML=`<b>${cart.reduce((s,i)=>s+i.qty,0)} item(ns)</b><br>Produtos: ${money(cartTotal())}<br>Entrega: calculada conforme escolha<br><strong>Total estimado: ${money(cartTotal()+12)}</strong>`;openModal("checkoutModal")}
function finishCheckout(e){e.preventDefault();
if(!cart.length)return toast("Seu carrinho está vazio");for(const item of cart){const p=products.find(x=>x.id===item.id);
if(item.qty>p.stock)return toast("Estoque insuficiente para "+p.name)}
 const fd=new FormData(e.target),delivery=fd.get("delivery"),freight=String(delivery).includes("Grátis")?0:12,total=cartTotal()+freight;cart.forEach(i=>products.find(p=>p.id===i.id).stock-=i.qty);
 const id="PC-2026-"+String(142+orders.length).padStart(4,"0");orders.unshift({id,customer:fd.get("customer"),date:new Date().toLocaleDateString("pt-BR"),total,status:"Pago",items:cart.reduce((s,i)=>s+i.qty,0),payment:fd.get("payment")});cart=[];save();updateCartCount();renderCart();closeDrawer();closeModal("checkoutModal");renderShop();toast("Compra "+id+" concluída! Estoque atualizado.")}

function prepareSchedule(serviceId){
 const service=SERVICES.find(s=>s.id===serviceId);$("#schedulePet").innerHTML=pets.map(p=>`<option>${p.name}</option>`).join("")+`<option value="novo">+ Cadastrar novo pet</option>`;
 $("#scheduleService").innerHTML=SERVICES.map(s=>`<option value="${s.id}" ${s.id===serviceId?"selected":""}>${s.name} — ${money(s.price)}</option>`).join("");
if(service)$("#scheduleAnimal").value=service.animal==="Todos"?"Cachorro":service.animal;
 $("#scheduleDate").min=new Date().toISOString().split("T")[0];$("#scheduleDate").value=new Date(Date.now()+86400000).toISOString().split("T")[0];updateScheduleSummary();openModal("scheduleModal");
}
function updateScheduleSummary(){const s=SERVICES.find(x=>x.id===Number($("#scheduleService").value));
if(!s)return;$("#scheduleSummary").innerHTML=`<b>${s.name}</b> • ${s.duration}<br>Valor estimado: <strong>${money(s.price)}</strong>`}
function submitSchedule(e){e.preventDefault();const service=SERVICES.find(s=>s.id===Number($("#scheduleService").value)),date=$("#scheduleDate").value,time=$("#scheduleTime").value;
if(bookings.some(b=>b.date===date&&b.time===time&&b.status!=="Cancelado"))return toast("Esse horário acabou de ser ocupado. Escolha outro.");bookings.push({id:Date.now(),pet:$("#schedulePet").value,animal:$("#scheduleAnimal").value,service:service.name,professional:$("#scheduleProfessional").value,date,time,notes:$("#scheduleNotes").value,status:"Confirmado",price:service.price});save();closeModal("scheduleModal");e.target.reset();toast("Agendamento confirmado e enviado ao painel!")}
function registerPet(e){e.preventDefault();const fd=new FormData(e.target),pet={id:Date.now(),...Object.fromEntries(fd.entries())};pets.push(pet);save();closeModal("petModal");e.target.reset();toast(pet.name+" foi cadastrado com sucesso!")}
function submitBusiness(e){e.preventDefault();closeModal("businessModal");e.target.reset();toast("Solicitação enviada para a equipe comercial!")}

function login(e){e.preventDefault();
if($("#loginUser").value==="Petclub"&&$("#loginPass").value==="Pet1234"){sessionStorage.setItem("pc_admin","true");closeModal("loginModal");showAdmin()}else{$("#loginError").textContent="Login ou senha incorretos.";$("#loginPass").value=""}}
function showAdmin(){if(sessionStorage.getItem("pc_admin")!=="true")return openModal("loginModal");$("#publicApp").style.display="none";$(".topbar").style.display="none";$("#adminApp").classList.add("active");renderAdmin("dashboard");window.scrollTo(0,0);refreshIcons()}
function logout(){sessionStorage.removeItem("pc_admin");$("#adminApp").classList.remove("active");$("#publicApp").style.display="block";$(".topbar").style.display="block";go("home");toast("Você saiu da administração")}
const statusClass=s=>s==="Pendente"||s==="Confirmado"?"warn":s==="Cancelado"||s==="Esgotado"?"bad":"";
function renderAdmin(section){adminSection=section;$$("[data-admin]").forEach(b=>b.classList.toggle("active",b.dataset.admin===section));const titles={dashboard:"Visão geral",bookings:"Agenda de serviços",clients:"Clientes e pets",services:"Catálogo de serviços",inventory:"Controle de estoque",restock:"Reposição de mercadorias",orders:"Pedidos e vendas",finance:"Contas e financeiro",suppliers:"Fornecedores"};$("#adminTitle").textContent=titles[section];$("#adminContent").innerHTML=`<div class="admin-content">${adminViews[section]()}</div>`;
bindAdmin(section);
const saved=adminRecords.filter(r=>r.type===(section==="finance"?"account":section==="suppliers"?"supplier":""));
if(saved.length){const wrap=$("#adminContent .admin-content");wrap.insertAdjacentHTML("beforeend",`<section class="panel" style="margin-top:18px"><div class="panel-head"><h2>Registros adicionados</h2><small>Dados salvos neste navegador</small></div>${saved.map(r=>`<p style="border-bottom:1px solid var(--line);padding:10px 0"><b>${r.description||r.company}</b><br><small>${r.type==="account"?`${r.type==='account'?r.status:''} • ${money(Number(r.value))} • ${r.date}`:`${r.category} • ${r.deadline} • ${r.contact}`}</small></p>`).join("")}</section>`)}
refreshIcons()}
const rowBookings=()=>bookings.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(b=>`<tr><td><b>${b.date.split("-").reverse().join("/")}</b><br>${b.time}</td><td><b>${b.pet}</b><br><small>${b.animal}</small></td><td>${b.service}<br><small>${b.professional}</small></td><td>${money(b.price)}</td><td><span class="status ${statusClass(b.status)}">${b.status}</span></td><td><select class="booking-status" data-booking="${b.id}"><option>${b.status}</option>${["Pendente","Confirmado","Em atendimento","Concluído","Cancelado"].filter(x=>x!==b.status).map(x=>`<option>${x}</option>`).join("")}</select></td></tr>`).join("");
const adminViews={
 dashboard:()=>{const low=products.filter(p=>p.stock<=p.min).length,revenue=orders.reduce((s,o)=>s+o.total,0);return`<div class="stats-grid"><div class="stat-card"><span><i data-lucide="calendar-check"></i></span><p>Agendamentos</p><h3>${bookings.length}</h3></div><div class="stat-card"><span><i data-lucide="users"></i></span><p>Pets cadastrados</p><h3>${pets.length}</h3></div><div class="stat-card"><span><i data-lucide="shopping-bag"></i></span><p>Faturamento</p><h3>${money(revenue)}</h3></div><div class="stat-card"><span><i data-lucide="triangle-alert"></i></span><p>Estoque crítico</p><h3>${low} itens</h3></div></div><div class="admin-grid"><section class="panel"><div class="panel-head"><h2>Próximos atendimentos</h2><button class="mini-btn primary" data-admin-jump="bookings">Ver agenda</button></div><table class="data-table"><thead><tr><th>Data</th><th>Pet</th><th>Serviço</th><th>Status</th></tr></thead><tbody>${bookings.slice(0,5).map(b=>`<tr><td>${b.date.split("-").reverse().join("/")} • ${b.time}</td><td><b>${b.pet}</b></td><td>${b.service}</td><td><span class="status ${statusClass(b.status)}">${b.status}</span></td></tr>`).join("")}</tbody></table></section><section class="panel"><div class="panel-head"><h2>Estoque crítico</h2></div>${products.filter(p=>p.stock<=p.min).slice(0,5).map(p=>`<div style="margin-bottom:15px"><div style="display:flex;justify-content:space-between;font-size:13px"><b>${p.name}</b><span class="negative">${p.stock} un.</span></div><div class="progress"><span style="width:${Math.min(100,p.stock/p.min*60)}%"></span></div></div>`).join("")}</section></div><section class="panel" style="margin-top:18px"><div class="panel-head"><h2>Vendas nos últimos 7 dias</h2></div><div class="chart-bars">${[62,78,48,92,71,84,100].map((h,i)=>`<div style="height:${h}%" data-day="${["Qui","Sex","Sáb","Dom","Seg","Ter","Hoje"][i]}"></div>`).join("")}</div></section>`},
 bookings:()=>`<section class="panel"><div class="panel-head"><div><h2>Agenda completa</h2><small>Altere o status para acompanhar cada atendimento.</small></div><button class="mini-btn primary" id="adminNewBooking">+ Novo agendamento</button></div><table class="data-table"><thead><tr><th>Data / hora</th><th>Pet</th><th>Serviço</th><th>Valor</th><th>Status</th><th>Atualizar</th></tr></thead><tbody>${rowBookings()}</tbody></table></section>`,
 clients:()=>`<section class="panel"><div class="panel-head"><div><h2>Clientes e pets</h2><small>Cadastros, saúde e histórico centralizados.</small></div><button class="mini-btn primary" id="adminNewPet">+ Cadastrar pet</button></div><table class="data-table"><thead><tr><th>Pet</th><th>Espécie</th><th>Raça</th><th>Idade / peso</th><th>Observações</th><th>Atendimentos</th></tr></thead><tbody>${pets.map(p=>`<tr><td><b>${p.name}</b></td><td>${p.species}</td><td>${p.breed}</td><td>${p.age}<br><small>${p.weight||"Não informado"}</small></td><td>${p.notes||"—"}</td><td>${bookings.filter(b=>b.pet===p.name).length}</td></tr>`).join("")}</tbody></table></section>`,
 services:()=>`<section class="panel"><div class="panel-head"><div><h2>Serviços cadastrados</h2><small>${SERVICES.length} opções para diferentes animais.</small></div></div><table class="data-table"><thead><tr><th>Serviço</th><th>Animal</th><th>Duração</th><th>Preço</th><th>Situação</th></tr></thead><tbody>${SERVICES.map(s=>`<tr><td><b>${s.name}</b><br><small>${s.desc}</small></td><td>${s.animal}</td><td>${s.duration}</td><td>${money(s.price)}</td><td><span class="status">Ativo</span></td></tr>`).join("")}</tbody></table></section>`,
 inventory:()=>`<section class="panel"><div class="panel-head"><div><h2>Estoque atual</h2><small>As compras da loja descontam quantidades automaticamente.</small></div><input id="inventorySearch" placeholder="Buscar produto"></div><table class="data-table"><thead><tr><th>Produto</th><th>Categoria</th><th>Animal</th><th>Preço</th><th>Estoque</th><th>Mínimo</th><th>Situação</th></tr></thead><tbody id="inventoryRows">${inventoryRows(products)}</tbody></table></section>`,
 restock:()=>`<div class="admin-grid"><section class="panel"><div class="panel-head"><h2>Registrar reposição</h2></div><form id="restockForm" class="form-grid" style="padding:0"><label class="full">Produto<select name="product">${products.map(p=>`<option value="${p.id}">${p.name} — atual: ${p.stock}</option>`).join("")}</select></label><label>Quantidade recebida<input name="qty" type="number" min="1" required></label><label>Preço de compra<input name="cost" type="number" min="0" step=".01" required></label><label>Fornecedor<select name="supplier"><option>Pet Distribuidora Brasil</option><option>AnimalMix Atacado</option><option>VetSupply</option></select></label><label>Data<input name="date" type="date" value="${new Date().toISOString().split("T")[0]}" required></label><button class="btn teal full">Confirmar entrada</button></form></section><section class="panel"><div class="panel-head"><h2>Últimas reposições</h2></div>${restocks.length?restocks.slice(0,7).map(r=>`<p style="border-bottom:1px solid var(--line);padding-bottom:10px"><b>${r.product}</b><br><small>+${r.qty} un. • ${r.date} • ${r.supplier}</small></p>`).join(""):`<div class="empty-admin">Nenhuma reposição registrada.</div>`}</section></div>`,
 orders:()=>`<div class="finance-cards"><div class="panel"><p>Pedidos registrados</p><h3>${orders.length}</h3></div><div class="panel"><p>Itens vendidos</p><h3>${orders.reduce((s,o)=>s+o.items,0)}</h3></div><div class="panel"><p>Total recebido</p><h3 class="positive">${money(orders.reduce((s,o)=>s+o.total,0))}</h3></div></div><section class="panel"><div class="panel-head"><h2>Histórico de pedidos</h2></div><table class="data-table"><thead><tr><th>Pedido</th><th>Data</th><th>Cliente</th><th>Itens</th><th>Total</th><th>Status</th></tr></thead><tbody>${orders.map(o=>`<tr><td><b>${o.id}</b></td><td>${o.date}</td><td>${o.customer}</td><td>${o.items}</td><td><b>${money(o.total)}</b></td><td><span class="status">${o.status}</span></td></tr>`).join("")}</tbody></table></section>`,
 finance:()=>{const revenue=orders.reduce((s,o)=>s+o.total,0),expenses=4380;return`<div class="finance-cards"><div class="panel"><p>Receitas</p><h3 class="positive">${money(revenue)}</h3><small>Vendas e serviços</small></div><div class="panel"><p>Contas a pagar</p><h3 class="negative">${money(expenses)}</h3><small>Fornecedores e despesas</small></div><div class="panel"><p>Saldo demonstrativo</p><h3>${money(revenue-expenses)}</h3><small>Resultado do período</small></div></div><section class="panel"><div class="panel-head"><h2>Contas e movimentações</h2><button class="mini-btn primary" id="newAccount">+ Nova conta</button></div><table class="data-table"><thead><tr><th>Descrição</th><th>Tipo</th><th>Vencimento</th><th>Valor</th><th>Status</th></tr></thead><tbody><tr><td>Fornecedor de rações</td><td>Despesa</td><td>30/08/2026</td><td class="negative">${money(2850)}</td><td><span class="status warn">Pendente</span></td></tr><tr><td>Energia e operação</td><td>Despesa</td><td>05/09/2026</td><td class="negative">${money(1530)}</td><td><span class="status warn">Pendente</span></td></tr><tr><td>Vendas da loja</td><td>Receita</td><td>Hoje</td><td class="positive">${money(revenue)}</td><td><span class="status">Recebido</span></td></tr></tbody></table></section>`},
 suppliers:()=>`<div class="business-grid"><article><i data-lucide="warehouse"></i><h3>Pet Distribuidora Brasil</h3><p>Rações, petiscos e acessórios.<br><b>Prazo: 5 dias úteis</b></p></article><article><i data-lucide="truck"></i><h3>AnimalMix Atacado</h3><p>Higiene, utensílios e brinquedos.<br><b>Prazo: 3 dias úteis</b></p></article><article><i data-lucide="stethoscope"></i><h3>VetSupply</h3><p>Produtos veterinários demonstrativos.<br><b>Prazo: 2 dias úteis</b></p></article><article><i data-lucide="plus"></i><h3>Novo fornecedor</h3><p>Cadastre outra empresa fornecedora.</p><button class="mini-btn primary" id="newSupplier">Cadastrar</button></article></div><section class="panel" style="margin-top:18px"><div class="panel-head"><h2>Solicitações de orçamento B2B</h2></div><table class="data-table"><thead><tr><th>Empresa</th><th>Interesse</th><th>Contato</th><th>Status</th></tr></thead><tbody><tr><td>Pet Shop Amigo Fiel</td><td>Compra no atacado</td><td>contato@exemplo.com</td><td><span class="status warn">Novo</span></td></tr></tbody></table></section>`
};
function inventoryRows(list){return list.map(p=>`<tr><td><b>${p.name}</b></td><td>${p.category}</td><td>${p.animal}</td><td>${money(p.price)}</td><td><b>${p.stock}</b></td><td>${p.min}</td><td><span class="status ${p.stock===0?"bad":p.stock<=p.min?"warn":""}">${p.stock===0?"Esgotado":p.stock<=p.min?"Repor estoque":"Disponível"}</span></td></tr>`).join("")}
function openAdminAction(type){
 const form=$("#adminActionForm");form.dataset.type=type;$("#adminActionTitle").textContent=type==="account"?"Cadastrar nova conta":"Cadastrar novo fornecedor";
 form.innerHTML=type==="account"?`<label class="full">Descrição<input name="description" required placeholder="Ex.: Compra de medicamentos"></label><label>Tipo<select name="type"><option>Despesa</option><option>Receita</option></select></label><label>Valor<input name="value" type="number" min="0.01" step=".01" required></label><label>Vencimento<input name="date" type="date" required></label><label>Status<select name="status"><option>Pendente</option><option>Pago</option><option>Recebido</option></select></label><button class="btn teal full">Salvar conta</button>`:`<label class="full">Empresa<input name="company" required></label><label>Categoria<input name="category" required placeholder="Ex.: Rações e acessórios"></label><label>Prazo<input name="deadline" required placeholder="Ex.: 5 dias úteis"></label><label>Contato<input name="contact" required placeholder="Telefone ou e-mail"></label><button class="btn teal full">Salvar fornecedor</button>`;
 openModal("adminActionModal");refreshIcons()
}
function bindAdmin(section){
$$("[data-admin-jump]").forEach(b=>b.onclick=()=>renderAdmin(b.dataset.adminJump));$$(".booking-status").forEach(s=>s.onchange=()=>{const b=bookings.find(x=>x.id===Number(s.dataset.booking));b.status=s.value;save();toast("Status atualizado");renderAdmin("bookings")});
if($("#adminNewBooking"))$("#adminNewBooking").onclick=()=>prepareSchedule(1);
if($("#adminNewPet"))$("#adminNewPet").onclick=()=>openModal("petModal");
if($("#inventorySearch"))$("#inventorySearch").oninput=e=>$("#inventoryRows").innerHTML=inventoryRows(products.filter(p=>p.name.toLowerCase().includes(e.target.value.toLowerCase())));
if($("#restockForm"))$("#restockForm").onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),p=products.find(x=>x.id===Number(fd.get("product"))),qty=Number(fd.get("qty"));p.stock+=qty;restocks.unshift({product:p.name,qty,cost:Number(fd.get("cost")),supplier:fd.get("supplier"),date:fd.get("date")});save();toast("Reposição registrada. Estoque atualizado!");renderAdmin("restock")};
if($("#newAccount"))$("#newAccount").onclick=()=>openAdminAction("account");
if($("#newSupplier"))$("#newSupplier").onclick=()=>openAdminAction("supplier")}

$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));$$("[data-action]").forEach(b=>b.onclick=()=>{const a=b.dataset.action;
if(a==="schedule")prepareSchedule(1);
if(a==="register-pet")openModal("petModal");
if(a==="schedule-vaccine")prepareSchedule(6);
if(a==="schedule-vet")prepareSchedule(5);
if(a==="business-form")openModal("businessModal");
if(a==="emergency")prepareSchedule(16)});$$("[data-animal]").forEach(b=>b.onclick=()=>{const a=b.dataset.animal;
if(a==="Cachorro"||a==="Gato"){filters.service=a;go("services")}else{filters.animal="Outros";go("shop")}});
$$("[data-close]").forEach(b=>b.onclick=()=>closeModal(b.dataset.close+"Modal"));$("#menuBtn").onclick=()=>$("#mobileNav").classList.toggle("open");$("#cartBtn").onclick=openDrawer;$("#overlay").onclick=closeDrawer;$("[data-close='cart']").onclick=closeDrawer;$("#adminBtn").onclick=()=>sessionStorage.getItem("pc_admin")==="true"?showAdmin():openModal("loginModal");$("#showPass").onclick=()=>$("#loginPass").type=$("#loginPass").type==="password"?"text":"password";
$("#productSearch").oninput=renderShop;$("#sortProducts").onchange=renderShop;$("#clearFilters").onclick=()=>{filters.category=filters.animal="Todos";$("#productSearch").value="";renderShop()};$("#scheduleService").onchange=updateScheduleSummary;$("#scheduleForm").onsubmit=submitSchedule;$("#petForm").onsubmit=registerPet;$("#checkoutForm").onsubmit=finishCheckout;$("#businessForm").onsubmit=submitBusiness;$("#loginForm").onsubmit=login;$("#logoutBtn").onclick=logout;$$("[data-admin]").forEach(b=>b.onclick=()=>renderAdmin(b.dataset.admin));
$("#schedulePet").onchange=e=>{if(e.target.value==="novo"){closeModal("scheduleModal");openModal("petModal")}};$$(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove("open")});document.addEventListener("keydown",e=>{if(e.key==="Escape"){$$(".modal.open").forEach(m=>m.classList.remove("open"));closeDrawer()}});
$("#searchBtn").onclick=()=>{go("shop");setTimeout(()=>$("#productSearch").focus(),150)};
$("#adminActionForm").onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),type=e.target.dataset.type;adminRecords.unshift({id:Date.now(),type,...Object.fromEntries(fd.entries())});save();closeModal("adminActionModal");e.target.reset();toast(type==="account"?"Conta cadastrada com sucesso!":"Fornecedor cadastrado com sucesso!");renderAdmin(type==="account"?"finance":"suppliers")};
updateCartCount();renderServices();renderShop();refreshIcons();
